### What is TensorFlow?
[Tensorflow](https.//www.tensorflow.org/) is an open-source end-to-end machine
learing library for preprocessing data,modelling data and serving models
### Whay use TensorFlow ?
Rather than building machine leraing and deep learing models from scratch,
it's more likely you'll use a library such as TensorFlow, this is 
because it contains many of most common machine leaaring 
functoin you'll want to use 

the first thing we'll do is import TensorFlow under the common alias `tf`.

In [1]:
# import tensorflow
import tensorflow as tf
print(tf.__version__) # find the version

2.9.1


### Creating Tensors with `tf.constant()`
`tf.constan()` is builtin function are able to read your data sources 
and automatically convert them to tensors and the later on, neural netwwork 
models will process for us.

In [3]:
# create a scalar
scalar = tf.constant(2) 
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [4]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# create a vector (more than 0 dimensions)
vector = tf.constant([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [7]:
# check the number of dimensions of a tensor
vector.ndim

1

In [8]:
# create matrix (more than 1 dimension)
matrix = tf.constant([[1,2,3],[4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [10]:
# check the number of dimensions of s tensor
matrix.ndim

2

In [12]:
# Create another matrix and define the datatype
another_matrix = tf.constant([[3,4,2],[9,4,3]] , dtype = tf.float16) # specify the datatype with 'dtype'
another_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[3., 4., 2.],
       [9., 4., 3.]], dtype=float16)>

In [13]:
# How about tensor ?(more than 2 dimension)
tensor = tf.constant([[[1,3,4],[4,5,6]],
                     [[5,3,4],[4,5,3]],
                     [[2,3,5],[4,2,1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 3, 4],
        [4, 5, 6]],

       [[5, 3, 4],
        [4, 5, 3]],

       [[2, 3, 5],
        [4, 2, 1]]])>

In [14]:
tensor.ndim

3

### Creating Tensors with `tf.Variable()`
You can also (although you likely rarely will ,because often,when working 
with data,tensor are created for you automatcally) create tensors using 
`tf.Variable()`

the diffenence between `tf.constant()` and `tf.Variable()` is tensors created
with `tf.constant()` are immutable (can't be changed can only be used to create a new
tensor), where as, tensor created with `tf.Variable()` are mutable (can be changed)

In [20]:
# create some tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([3,4,5])
unchangeable_tensor = tf.constant([4,5,2])

changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([3, 4, 5])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 2])>)

Now let's try to change one of the elements of the changeable tensor

In [21]:
# will error (rquires the .assign() method)
changeable_tensor[1] = 8

TypeError: 'ResourceVariable' object does not support item assignment

To change an element of a `tf.Variable()` tensor requires the `assign()`
method

In [23]:
# Won't error 
changeable_tensor[1].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([9, 9, 5])>

Now let's try to change a value in a `tf.constant()` tensor.

In [24]:
# Will error (can't change tf.t=constant())
unchangeable_tensor[1].assign(3)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Which one should you use ?
`tf.Variable()` or `tf.constant()`
it will depend on what your proplem requires . However, most of the 
time , TensorFlow will automatcally choose for you( when loading data or 
 modelling data)

### Create random tensors with `tf.random.Generator`

In [25]:
# Create two random
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(4,5)) # create tensor from a normal dstribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (4,5))

random_1 , random_2

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085]],
       dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085]],
       dtype=float32)>)

### Shuffle the order of a tensor

In [9]:
# Shuffle a tensor
not_shuffled = tf.constant([[1,2,3],
                           [4,5,6],
                           [7,8,9]])
# Gets different results each item
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])>

In [15]:
# Shuffle in the same order every time
tf.random.set_seed(42)
# Set the operation random seed
tf.random.shuffle(not_shuffled ,seed= 42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

Other ways to make tensors
`tf.zeros()` and `tf.ones()`

In [17]:
# make a tensor of all oens
tf.ones(shape = (3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [19]:
# make a tensor of all zeros
tf.zeros(shape = (3,3))


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

you also trun numpy arrays into tensor 

Remember, the main difference between tensor and NumPy arrays
is that tensors can be run on GPUs 


In [28]:
import numpy as np
numpy_A = np.arange(1,25)
tensor = tf.constant(numpy_A , shape = [2 , 3 ,4])
numpy_A , tensor

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

Getting information from tensors(shape, rank ,size)

* **Shape:** the length(number of elements) of each the dimensions of the tensors
* **Rank:** the number of tensor dimensions,A scalar has rank 0 , a vector has rank 1
a tensor has rank n
* **Axis** or **Dimensions:** A particular dimensions of the a tensor 
* **Size:** the total number of items in the tensor

In [22]:
rank_tensor = tf.ones([2,3,4,5])
rank_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [24]:
# Get various attributes of tensor
print("Datatype of very element:",rank_tensor)
print("Number of dimensions (rank):",rank_tensor.ndim)
print("Shape of tensor:",rank_tensor.shape)
print("Total number of elements:",tf.size(rank_tensor))

Datatype of very element: tf.Tensor(
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]], shape=(2, 3, 4, 5), dtype=float32)
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Total number of elements: tf.Tensor(120, shape=(), dtype=int32)


### Manipulating tensor (tensor operations)

### Basic operations

you can perform manay of the basic mathatical operations directly 
on tensor using python operators such as . `+`,`-`,`*`.

In [25]:
# you can add values to a tensor using addition oprators
tensor = tf.constant([[4,2],[6,8]])
tensor + 12

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 14],
       [18, 20]])>

In [26]:
# multiplication
tensor * 7

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 14],
       [42, 56]])>

In [28]:
# Subtraction
tensor - 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 0],
       [4, 6]])>

you can also using the equivalent TensorFlow function

In [29]:
# use tensorflow function equivalent of the `*`(multiply)
tf.multiply(tensor , 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 10],
       [30, 40]])>

In [31]:
# matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor , tensor)

tf.Tensor(
[[4 2]
 [6 8]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 24],
       [72, 76]])>

In [32]:
# matirx multiplication with python `@`
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 24],
       [72, 76]])>

In [2]:
# Create (4,3) tensor
x = tf.constant([[1,3,4],[8,4,9],[0,8,1],[3,4,2]])
# Create another (4,3)
y = tf.constant([[2,3,1],[3,4,7],[5,4,9],[2,1,6]])
x , y

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[1, 3, 4],
        [8, 4, 9],
        [0, 8, 1],
        [3, 4, 2]])>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[2, 3, 1],
        [3, 4, 7],
        [5, 4, 9],
        [2, 1, 6]])>)

In [35]:
# Try matrix multiply them (will error)
x @ y

InvalidArgumentError: Matrix size-incompatible: In[0]: [4,3], In[1]: [4,3] [Op:MatMul]

In [37]:
# Example of reshape (4,3) -> (3,4)
tf.reshape(y , shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 3, 1, 3],
       [4, 7, 5, 4],
       [9, 2, 1, 6]])>

In [38]:
# Try multiplication with reshaped
x @ tf.reshape(y,shape = (3,4))

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 50,  32,  20,  39],
       [113,  70,  37,  94],
       [ 41,  58,  41,  38],
       [ 40,  41,  25,  37]])>

In [39]:
# Example of tranpose (4,3) -> (3,4)
tf.transpose(x)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 8, 0, 3],
       [3, 4, 8, 4],
       [4, 9, 1, 2]])>

In [40]:
# Try multipliction with transposed
x @ tf.transpose(y)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 15,  43,  53,  29],
       [ 37, 103, 137,  74],
       [ 25,  39,  41,  14],
       [ 20,  39,  49,  22]])>

In [45]:
# you can achieve the same result with parameter
tf.matmul(a=x,b=y,transpose_a=False ,transpose_b=True)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 15,  43,  53,  29],
       [ 37, 103, 137,  74],
       [ 25,  39,  41,  14],
       [ 20,  39,  49,  22]])>

### The dot product

In [4]:
# perform the dot product on X and Y (requires x to be trnsposted)
tf.tensordot(tf.transpose(x),y, axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 32,  38,  75],
       [ 66,  61, 127],
       [ 44,  54,  88]])>

In [8]:
# check shape of Y , reshape Y and transpose Y
y.shape , tf.reshape(y,(3,4)).shape ,tf.transpose(y).shape

(TensorShape([4, 3]), TensorShape([3, 4]), TensorShape([3, 4]))

In [12]:
# check values of Y, reshpe Y and transpose Y
print(f"Normal Y :\n {y}") # \n for newline
print(f"reshape Y: \n {tf.reshape(y,(3,4))}")
print(f"transpose Y: \n {tf.transpose(y)}")

Normal Y :
 [[2 3 1]
 [3 4 7]
 [5 4 9]
 [2 1 6]]
reshape Y: 
 [[2 3 1 3]
 [4 7 5 4]
 [9 2 1 6]]
transpose Y: 
 [[2 3 5 2]
 [3 4 4 1]
 [1 7 9 6]]


You cannot add a float tensor and an integer tensor

In [6]:
tf.constant(20) + tf.constant(1.0)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

Else you cannot even add a 32-bit float and a 64-bit float

In [7]:
tf.constant(3.0) + tf.constant(1.2 , dtype = tf.float64)

<tf.Tensor: shape=(), dtype=float32, numpy=4.2>

### Changing thr datatype of a tensor 
with `tf.cast()`

In [14]:
# Create a new tensor with default datatype(int32)
a = tf.constant([1,2,3,4,5])
# Create a new a tensor with default datatype(float32)
b = tf.constant([6.0,7.0,8.0,9.0,10.0])
a , b

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 6.,  7.,  8.,  9., 10.], dtype=float32)>)

In [22]:
# change from int32 to int64
a = tf.cast(a,dtype=tf.int64)
a

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5], dtype=int64)>

In [24]:
# change from int64 to float16
a = tf.cast(a , dtype = tf.float16)
a

<tf.Tensor: shape=(5,), dtype=float16, numpy=array([1., 2., 3., 4., 5.], dtype=float16)>

In [17]:
# change from float32 to float16
b = tf.cast(b,dtype = tf.float16)
b

<tf.Tensor: shape=(5,), dtype=float16, numpy=array([ 6.,  7.,  8.,  9., 10.], dtype=float16)>

### Getting the absolute value

In [26]:
# Create tensor with negative values
C = tf.Variable([-3,-8,-5])
C

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([-3, -8, -5])>

In [27]:
# Get the absolut value
tf.abs(C)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 8, 5])>

### finding the min,max,mean,sum,(aggregation)
You can quickly aggergate (perform a calculation on whole tensor)
tensors to find things like the minimum value,maximum value,mean and sum all elements.
To do so,aggergation methods typically have the syntax `reduce()_[action]`
such as:
* `tf.reduce_min()`-find the minimum value in a tensor
* `tf.reduce_max()` - find the maximum value in a tensor
* `tf.reduce_mean()` - find the mean of all elements in a tensor
* `tf.reduce_sum()` - find the sum of all elements in a tensor
* **Note** typically, each of these is under the `math` module,e.g.
`tf.math.reduce_min()`, but you can use the alias `tf.reduce_min()`

In [31]:
# Create a tensor with 50 random value between 0 and 100
D = tf.Variable(np.random.randint(low=0 , high = 100 ,size = 50))
D

<tf.Variable 'Variable:0' shape=(50,) dtype=int32, numpy=
array([ 0, 39, 91, 81, 25, 85, 17, 40, 21, 16, 24,  3, 33, 49,  7, 49, 59,
       26, 11, 28, 14, 71, 48, 16, 48, 28, 29,  5, 80, 40, 92, 47,  7, 35,
       20, 74,  2, 33, 90, 58, 46, 73, 46, 26, 66, 72, 32, 97, 17, 61])>

In [32]:
# find the maximum
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [33]:
# find the minimum
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [34]:
# find the mean
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=41>

In [35]:
# find the sumation
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=2077>

### finding the positional maximum and minimum
* `tf.argmax()` - find the position of the maximum element in a given tensor
* `tf.argmin()` - find the position of the minimum element in a given tensor

In [38]:
# Create a tensor the 50 value between 0 and 1
E = tf.constant(np.random.random(50))
E

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.54376682, 0.82207729, 0.58165692, 0.55538636, 0.16384251,
       0.34780264, 0.164292  , 0.35238074, 0.73014143, 0.5187889 ,
       0.98628477, 0.00607107, 0.38611056, 0.08644678, 0.33319544,
       0.03077513, 0.69580692, 0.54103679, 0.88035362, 0.21665809,
       0.80506309, 0.89101156, 0.04689885, 0.05980998, 0.82600522,
       0.47516662, 0.26449945, 0.61338363, 0.33064297, 0.29871419,
       0.6190014 , 0.57708566, 0.53365022, 0.0659082 , 0.65318207,
       0.08330534, 0.30952765, 0.78982358, 0.2444955 , 0.52865022,
       0.69607377, 0.42980411, 0.7315938 , 0.67786852, 0.00444221,
       0.34987897, 0.53840036, 0.79679314, 0.00923893, 0.27267022])>

In [42]:
# Find the maximum element position
tf.argmax(E).numpy()

10

In [41]:
# Find the minimum element position
tf.argmin(E).numpy()

44

In [46]:
print(f"Using tf.argmax to index E : {E[tf.argmax(E).numpy()]}")
print(f"Using tf.argmin to index E : {E[tf.argmin(E).numpy()]}")
print(f"Are two max value same?: {E[tf.argmax(E).numpy()] == tf.reduce_max(E)}")


Using tf.argmax to index E : 0.9862847743568992
Using tf.argmin to index E : 0.00444220956390351
Are two max value same?: True


### Squeezing a tensor (removing all single dimensions)
If you need to remove single-dimensions from a tensor (dimension with size 1)
you can use `tf.squeeze()`
* `tf.squeeze ()` - remove all dimensions of 1 from a tensor

In [48]:
# Create a rank 5 (5 dimensions) tensor of 50 number beween 0 and 100
D = tf.constant(np.random.randint(0,100,50),shape=(1,1,1,1,50))
D.shape , D.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [49]:
# Squeeze tensor D
D_squeezed = tf.squeeze(D)
D_squeezed.shape , D_squeezed.ndim

(TensorShape([50]), 1)

### One-hot encoding


In [52]:
# Create a list of indices
one_list = [0,1,2,3]
# One hot encode them
tf.one_hot(one_list,depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Squaring, log, square root
* `tf.square()` - get the square of every value in a tensor
* `tf.sqrt()` - get the squareroot of the every value in a tensor (**Note:**
the elements need to floats)
* `tf.math.log()` - get the natural log of the every value (**Note:**
the elements need to floats)

In [53]:
# Create a new tensor
F= tf.constant(np.arange(1, 8))
F

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7])>

In [54]:
# Square it
tf.square(F)

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49])>

In [55]:
# Find the squrateroot (will error)needs to be float
tf.sqrt(F)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [56]:
# change F to float32
F = tf.cast(F,dtype = tf.float32)
F

<tf.Tensor: shape=(7,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)>

In [57]:
# find the square root
tf.sqrt(F)

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512], dtype=float32)>

In [58]:
# find the log also need to be non_integer
tf.math.log(F)

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459101], dtype=float32)>

### Manipulating `tf.Variable()` tensor
Tensor creared with `tf.Variable()` can be changed in place using methods such
as:
`.assign()` - assign a ddiferent value to a particular index of a variable
tensor
`add_assign()` - add to an existing value and reassign it at a particular
index of a variable tensor 

In [60]:
# Create a variable tensor
H = tf.Variable(np.arange(1,6))
H

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [61]:
# assign the fianl value a new value of 15
H.assign([1,2,3,4,15]) 

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 1,  2,  3,  4, 15])>

In [63]:
H.assign_add([5,5,5,5,5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 6,  7,  8,  9, 20])>

### Tensors and NumPy

we have seen some examples of tensor interact with Numpy arrays, such as,
using Numpy arrays to create tensor
Tensors can also be converted to Numpy arrays ussing:
* `np.array()` - pass a tensor to convert to an ndarray (numpy main datatype)
* `tensor.numpy()` - call on a tensor to convert to an ndarray

In [64]:
# Create a tensor from numpy array
I = tf.constant(np.array([3,4,8]))
I

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 8])>

In [65]:
# Convert a tensor j to Numpy with np.numpy()
np.array(I) , type(np.array(I))

(array([3, 4, 8]), numpy.ndarray)

### TensorFlow Functions


In [8]:
def f_cube(x):
   return x**3

print(f_cube(tf.constant(4)))

t_cube = tf.function(f_cube)

print(t_cube(3))


@tf.function
def f(x):
   return x * 2

f(2)


tf.Tensor(64, shape=(), dtype=int32)
tf.Tensor(27, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=4>

### The Data API


In [2]:
x = tf.range(10)
data = tf.data.Dataset.from_tensor_slices(x)

# for item in data:
#    print(item)

# else you can use this function
data = tf.data.Dataset.range(10)

for item in data:
   print(item)


tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


You can apply all sorts of transformations to it by calling its
transformation methods

In [3]:
data = data.repeat(4).batch(7)

for item in data:
   print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int64)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int64)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int64)
tf.Tensor([8 9 0 1 2 3 4], shape=(7,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)


Shuffling the data

In [5]:
data = tf.data.Dataset.range(10).repeat(3)
data = data.shuffle(buffer_size=5,seed = 42).batch(7)
for item in data:
   print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)
